import os
from setuptools import setup

# requirements is generated by pipreqs <project_path>
with open('requirements.txt') as f:
    required = f.read().splitlines()


setup(
   name='logger',
   version='1.0',
   description='Machine learning experiments logger',
   author='Ahmad El Sallab',
   author_email='ahmad.elsallab@gmail.com',
   packages=['experiments'],  #same as name
   install_requires=required, #external packages as dependencies
)